// Generated by aistatus — do not edit by hand.
// Re-run: aistatus install-hooks --agent opencode
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PY = __PY__;
const AI_STATUS_HOME = __AI_STATUS_HOME__;
const ALLOWED = __EVENTS__;
const LOG = path.join(AI_STATUS_HOME, "opencode.log");
const lastTitle = new Map();

function log(line) {
  try {
    fs.mkdirSync(AI_STATUS_HOME, { recursive: true });
    fs.appendFileSync(LOG, new Date().toISOString() + "  " + line + "\n");
  } catch (e) {}
}

function forward(eventType, properties) {
  const payload = JSON.stringify({
    session_id: properties.sessionID ?? properties.sessionId ?? null,
    session_name: properties.session_name ?? null,
    event: eventType,
    properties,
  });
  const child = spawn(PY, ["-m", "aistatus", "hook", "--agent", "opencode", "--default-state", ""], {
    env: { ...process.env, AISTATUS_HOME: AI_STATUS_HOME },
    stdio: ["pipe", "ignore", "pipe"],
  });
  let err = "";
  child.stderr.on("data", (d) => { err += d.toString(); });
  child.on("exit", (code) => {
    if (code) log(`aside hook exit=${code} ${eventType}${err ? " :: " + err.trim().split("\n").slice(-2).join(" | ") : ""}`);
  });
  child.stdin.end(payload);
}

function pick(value, ...keys) {
  for (const k of keys) if (value?.[k] != null) return value[k];
  return undefined;
}

export const AistatusPlugin = async () => {
  log("plugin loaded");
  return {
    event: async ({ event }) => {
      const type = event?.type;
      if (!type || !ALLOWED.includes(type)) return;
      const props = event?.properties ?? event?.data ?? {};
      const info = props.info ?? {};
      const sessionID = pick(props, "sessionID", "sessionId")
        ?? pick(info, "id")
        ?? pick(event, "sessionID", "sessionId");
      if (!sessionID) return;
      const title = info.title ?? props.title;
      // session.updated fires often; only forward when the title actually changes.
      if (type === "session.updated") {
        if (!title || lastTitle.get(sessionID) === title) return;
      }
      if (title) lastTitle.set(sessionID, title);
      log(`${type} sid=${sessionID} title=${JSON.stringify(title ?? null)} status=${JSON.stringify(pick(props, "status"))}`);
      forward(type, { ...props, sessionID, session_name: title });
    },
  };
};
