// Generated by aistatus — do not edit by hand.
// Re-run: aistatus install-hooks --agent opencode
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PY = __PY__;
const AI_STATUS_HOME = __AI_STATUS_HOME__;
const ALLOWED = __EVENTS__;
const LOG = path.join(AI_STATUS_HOME, "opencode.log");
const lastTitle = new Map();
const lastDir = new Map();
const lastQuestion = new Map();   // part id -> last status we forwarded
const lastThinking = new Map();   // part id -> already reported thinking
const pendingQuestion = new Set(); // sessions currently blocked on a question
const inflight = new Map();        // sessionID -> running tool count
const heartbeats = new Map();      // sessionID -> interval id

const HEARTBEAT_MS = 180000;       // refresh while a tool runs (3 min)

function startHeartbeat(sid) {
  if (heartbeats.has(sid)) return;
  const id = setInterval(() => {
    if (!inflight.get(sid)) {
      clearInterval(id);
      heartbeats.delete(sid);
      return;
    }
    forward("heartbeat", { sessionID: sid });
  }, HEARTBEAT_MS);
  heartbeats.set(sid, id);
}

function stopHeartbeat(sid) {
  if (inflight.get(sid)) return;
  const id = heartbeats.get(sid);
  if (id) {
    clearInterval(id);
    heartbeats.delete(sid);
  }
}

const QUESTION_TOOL = "question";

function log(line) {
  try {
    fs.mkdirSync(AI_STATUS_HOME, { recursive: true });
    fs.appendFileSync(LOG, new Date().toISOString() + "  " + line + "\n");
  } catch (e) {}
}

function safeStringify(value) {
  try {
    return JSON.stringify(value);
  } catch (e) {
    const seen = new Set();
    return JSON.stringify(value, (k, v) => {
      if (typeof v === "object" && v !== null) {
        if (seen.has(v)) return undefined;
        seen.add(v);
      }
      return v;
    });
  }
}

function forward(eventType, properties) {
  const payload = safeStringify({
    session_id: properties.sessionID ?? properties.sessionId ?? null,
    session_name: properties.session_name ?? null,
    session_dir: properties.session_dir ?? properties.info?.directory ?? properties.directory ?? null,
    message: properties.message ?? null,
    event: eventType,
    properties,
  });
  const child = spawn(PY, ["-m", "aistatus", "hook", "--agent", "opencode", "--default-state", "", "--verbose"], {
    env: { ...process.env, AISTATUS_HOME: AI_STATUS_HOME },
    stdio: ["pipe", "ignore", "pipe"],
  });
  let err = "";
  child.stderr.on("data", (d) => { err += d.toString(); });
  child.on("error", (e) => log(`hook spawn error ${eventType}: ${e}`));
  child.on("exit", (code) => {
    if (code || eventType.startsWith("question")) {
      log(`aside hook exit=${code} ${eventType}${err ? " :: " + err.trim().split("\n").slice(-2).join(" | ") : ""}`);
    }
  });
  child.stdin.end(payload);
}

function pick(value, ...keys) {
  for (const k of keys) if (value?.[k] != null) return value[k];
  return undefined;
}

export const AistatusPlugin = async () => {
  log("plugin loaded");
  return {
    // Busy while a tool runs (these are hooks, not events).
    "tool.execute.before": async (input) => {
      const sid = input?.sessionID;
      if (!sid) return;
      inflight.set(sid, (inflight.get(sid) ?? 0) + 1);
      startHeartbeat(sid);
      if (pendingQuestion.has(sid)) return;
      log(`tool.before sid=${sid} tool=${input?.tool}`);
      forward("tool.before", { sessionID: sid, tool: input?.tool });
    },
    "tool.execute.after": async (input) => {
      const sid = input?.sessionID;
      if (!sid) return;
      inflight.set(sid, Math.max(0, (inflight.get(sid) ?? 1) - 1));
      stopHeartbeat(sid);
      if (pendingQuestion.has(sid)) return;
      forward("tool.after", { sessionID: sid, tool: input?.tool });
    },
    event: async ({ event }) => {
      const type = event?.type;
      if (!type || !ALLOWED.includes(type)) return;
      const props = event?.properties ?? event?.data ?? {};
      const info = props.info ?? {};
      const sessionID = pick(props, "sessionID", "sessionId")
        ?? pick(info, "id")
        ?? pick(event, "sessionID", "sessionId");
      if (!sessionID) return;
      const title = info.title ?? props.title;
      const dir = info.directory ?? props.directory;

      // The `question` tool blocks on the user choosing an option — surface it as
      // blocked (opencode keeps session.status busy, so it needs special handling).
      if (type === "message.part.updated") {
        const part = props.part ?? {};
        // Model reasoning → thinking (once per part).
        if (part.type === "reasoning") {
          const rid = part.id ?? sessionID;
          if (lastThinking.get(rid) !== "done") {
            lastThinking.set(rid, "done");
            if (!pendingQuestion.has(sessionID)) {
              log(`thinking sid=${sessionID}`);
              forward("thinking", { sessionID });
            }
          }
          return;
        }
        if (part.type === "tool" && part.tool === QUESTION_TOOL) {
          const status = part.state?.status;
          const qid = part.id ?? sessionID;
          if (status === "running") {
            pendingQuestion.add(sessionID);
            if (lastQuestion.get(qid) !== "running") {
              lastQuestion.set(qid, "running");
              const text = part.state?.input?.questions?.[0]?.question ?? null;
              log(`question.asked sid=${sessionID} ${JSON.stringify(text)}`);
              forward("question.asked", { sessionID, message: text, part: { id: qid, type: "tool", tool: QUESTION_TOOL, state: { status: "running" } } });
            }
          } else if (status === "completed" || status === "error") {
            pendingQuestion.delete(sessionID);
            if (lastQuestion.get(qid) !== "done") {
              lastQuestion.set(qid, "done");
              log(`question.replied sid=${sessionID} status=${status}`);
              forward("question.replied", { sessionID, part: { id: qid, type: "tool", tool: QUESTION_TOOL, state: { status } } });
            }
          }
        }
        return;
      }

      // While a question is pending, ignore busy so it doesn't overwrite blocked.
      if (type === "session.status") {
        const st = props.status?.type;
        if (st === "idle") pendingQuestion.delete(sessionID);
        else if (st === "busy" && pendingQuestion.has(sessionID)) return;
      }

      // session.updated fires often; only forward when title/directory changes.
      if (type === "session.updated") {
        const titleChanged = title && lastTitle.get(sessionID) !== title;
        const dirChanged = dir && lastDir.get(sessionID) !== dir;
        if (!titleChanged && !dirChanged) return;
      }
      if (title) lastTitle.set(sessionID, title);
      if (dir) lastDir.set(sessionID, dir);
      log(`${type} sid=${sessionID} title=${JSON.stringify(title ?? null)} dir=${JSON.stringify(dir ?? null)} status=${JSON.stringify(pick(props, "status"))}`);
      forward(type, { ...props, sessionID, session_name: title, session_dir: dir });
    },
  };
};
