// Generated by aistatus — do not edit by hand.
// Re-run: aistatus install-hooks --agent opencode
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PY = __PY__;
const AI_STATUS_HOME = __AI_STATUS_HOME__;
const ALLOWED = __EVENTS__;
const LOG = path.join(AI_STATUS_HOME, "opencode.log");
const lastTitle = new Map();
const lastDir = new Map();
const lastQuestion = new Map();   // part id -> last status we forwarded
const lastThinking = new Map();   // part id -> already reported thinking
const pendingQuestion = new Set(); // sessions currently blocked on a question
const pendingPermission = new Set(); // sessions waiting on a permission prompt
const inflight = new Map();        // sessionID -> running tool count
const heartbeats = new Map();      // sessionID -> interval id

const HEARTBEAT_MS = 180000;       // refresh while a tool runs (3 min)

function startHeartbeat(sid) {
  if (heartbeats.has(sid)) return;
  const id = setInterval(() => {
    if (!inflight.get(sid)) {
      clearInterval(id);
      heartbeats.delete(sid);
      return;
    }
    forward("heartbeat", { sessionID: sid });
  }, HEARTBEAT_MS);
  heartbeats.set(sid, id);
}

function stopHeartbeat(sid) {
  if (inflight.get(sid)) return;
  const id = heartbeats.get(sid);
  if (id) {
    clearInterval(id);
    heartbeats.delete(sid);
  }
}

const QUESTION_TOOL = "question";

// Host terminal/desktop detection (drives which app the menu bar jumps to).
const TERM_HOSTS = {
  "iTerm.app": "com.googlecode.iterm2",
  "vscode": "com.microsoft.VSCode",
  "Apple_Terminal": "com.apple.Terminal",
  "WarpTerminal": "dev.warp.Warp-Stable",
  "WezTerm": "com.github.wez.wezterm",
  "Hyper": "co.zeit.hyper",
  "Tabby": "org.tabby",
};
function detectHost() {
  try { if (process.versions && process.versions.electron) return "ai.opencode.desktop"; } catch (e) {}
  const tp = process.env.TERM_PROGRAM || "";
  if (TERM_HOSTS[tp]) return TERM_HOSTS[tp];
  if (tp) return null;                       // unknown terminal → let the app decide
  return "ai.opencode.desktop";              // no terminal info → desktop app
}
const HOST = detectHost();
const HOST_REF = process.env.ITERM_SESSION_ID || process.env.TERM_SESSION_ID || null;

function log(line) {
  try {
    fs.mkdirSync(AI_STATUS_HOME, { recursive: true });
    fs.appendFileSync(LOG, new Date().toISOString() + "  " + line + "\n");
  } catch (e) {}
}

function safeStringify(value) {
  try {
    return JSON.stringify(value);
  } catch (e) {
    try {
      const seen = new Set();
      return JSON.stringify(value, (k, v) => {
        if (typeof v === "object" && v !== null) {
          if (seen.has(v)) return undefined;
          seen.add(v);
        }
        return v;
      });
    } catch (e2) {
      log(`stringify failed: ${e2 && e2.message}`);
      return "{}";
    }
  }
}

// Concurrent forwards with a timeout. Ordering is guaranteed by the store's
// monotonic `seq` (stale writes are ignored), so we never serialize — a single
// slow/hung child must not stall every later event.
const HOOK_TIMEOUT_MS = 8000;

function forward(eventType, properties) {
  const payload = safeStringify({
    session_id: properties.sessionID ?? properties.sessionId ?? null,
    session_name: properties.session_name ?? null,
    session_dir: properties.session_dir ?? properties.info?.directory ?? properties.directory ?? null,
    session_host: HOST,
    session_ref: HOST_REF,
    message: properties.message ?? null,
    seq: Date.now(),
    event: eventType,
    properties,
  });
  let child;
  try {
    child = spawn(PY, ["-m", "aistatus", "hook", "--agent", "opencode", "--default-state", "", "--verbose"], {
      env: { ...process.env, AISTATUS_HOME: AI_STATUS_HOME },
      stdio: ["pipe", "ignore", "pipe"],
    });
  } catch (e) {
    log(`hook spawn threw ${eventType}: ${e}`);
    return;
  }
  let err = "";
  let done = false;
  const finish = (reason) => {
    if (done) return;
    done = true;
    clearTimeout(timer);
    const msg = err.trim();
    if (reason || msg || eventType.startsWith("question")) {
      log(`hook ${reason ?? "ok"} ${eventType}${msg ? " :: " + msg.split("\n").slice(-2).join(" | ") : ""}`);
    }
  };
  const timer = setTimeout(() => {
    try { child.kill("SIGKILL"); } catch (e) {}
    finish("timeout");
  }, HOOK_TIMEOUT_MS);
  child.stderr.on("data", (d) => { err += d.toString(); });
  child.on("error", (e) => { err += String(e); finish("spawn-error"); });
  child.on("exit", (code) => finish(code ? "exit=" + code : null));
  try {
    child.stdin.end(payload);
  } catch (e) {
    err += String(e);
    finish("stdin-error");
  }
}

// A permission / question prompt is usually announced milliseconds *before* the
// `tool.execute.before` "busy" that triggered it. Re-sending the blocked event a
// moment later gives it a higher `seq`, so "blocked" always wins the store's
// ordering even when the two hook processes race.
const REINFORCE_MS = 400;
const reinforceTimers = new Map();

function cancelReinforce(sid) {
  const t = reinforceTimers.get(sid);
  if (t) { clearTimeout(t); reinforceTimers.delete(sid); }
}

function reinforce(eventType, properties, sid) {
  cancelReinforce(sid);
  const t = setTimeout(() => {
    reinforceTimers.delete(sid);
    if (!pendingQuestion.has(sid) && !pendingPermission.has(sid)) return;   // already answered
    log(`reinforce ${eventType} sid=${sid}`);
    forward(eventType, properties);
  }, REINFORCE_MS);
  reinforceTimers.set(sid, t);
}

function pick(value, ...keys) {
  for (const k of keys) if (value?.[k] != null) return value[k];
  return undefined;
}

export const AistatusPlugin = async () => {
  log(`plugin loaded host=${HOST} ref=${HOST_REF ?? "null"}`);
  return {
    // Busy while a tool runs (these are hooks, not events).
    "tool.execute.before": async (input) => {
      const sid = input?.sessionID;
      if (!sid) return;
      inflight.set(sid, (inflight.get(sid) ?? 0) + 1);
      startHeartbeat(sid);
      // The question tool means "waiting for the user" → blocked, not busy.
      if (input?.tool === QUESTION_TOOL) {
        pendingQuestion.add(sid);
        return;
      }
      if (pendingQuestion.has(sid) || pendingPermission.has(sid)) return;
      log(`tool.before sid=${sid} tool=${input?.tool}`);
      forward("tool.before", { sessionID: sid, tool: input?.tool });
    },
    "tool.execute.after": async (input) => {
      const sid = input?.sessionID;
      if (!sid) return;
      inflight.set(sid, Math.max(0, (inflight.get(sid) ?? 1) - 1));
      stopHeartbeat(sid);
      // question.replied already returns to working.
      if (input?.tool === QUESTION_TOOL) {
        pendingQuestion.delete(sid);
        return;
      }
      if (pendingQuestion.has(sid) || pendingPermission.has(sid)) return;
      forward("tool.after", { sessionID: sid, tool: input?.tool });
    },
    event: async ({ event }) => {
      const type = event?.type;
      if (!type || !ALLOWED.includes(type)) return;
      const props = event?.properties ?? event?.data ?? {};
      const info = props.info ?? {};
      const sessionID = pick(props, "sessionID", "sessionId")
        ?? pick(info, "id")
        ?? pick(event, "sessionID", "sessionId");
      if (!sessionID) return;
      const title = info.title ?? props.title;
      const dir = info.directory ?? props.directory;

      // A permission prompt keeps the session blocked; remember it.
      if (type === "permission.asked" || type === "permission.updated") {
        pendingPermission.add(sessionID);
        reinforce(type, { ...props, sessionID, session_name: title, session_dir: dir }, sessionID);
      } else if (type === "permission.replied") {
        pendingPermission.delete(sessionID);
        cancelReinforce(sessionID);
      }

      // The `question` tool blocks on the user choosing an option — surface it as
      // blocked (opencode keeps session.status busy, so it needs special handling).
      if (type === "message.part.updated") {
        const part = props.part ?? {};
        // Model reasoning → thinking (once per part).
        if (part.type === "reasoning") {
          const rid = part.id ?? sessionID;
          if (lastThinking.get(rid) !== "done") {
            lastThinking.set(rid, "done");
            if (!pendingQuestion.has(sessionID)) {
              log(`thinking sid=${sessionID}`);
              forward("thinking", { sessionID });
            }
          }
          return;
        }
        if (part.type === "tool" && part.tool === QUESTION_TOOL) {
          const status = part.state?.status;
          const qid = part.id ?? sessionID;
          if (status === "running") {
            pendingQuestion.add(sessionID);
            if (lastQuestion.get(qid) !== "running") {
              lastQuestion.set(qid, "running");
              const text = part.state?.input?.questions?.[0]?.question ?? null;
              log(`question.asked sid=${sessionID} ${JSON.stringify(text)}`);
              const props2 = { sessionID, message: text, part: { id: qid, type: "tool", tool: QUESTION_TOOL, state: { status: "running" } } };
              forward("question.asked", props2);
              reinforce("question.asked", props2, sessionID);
            }
          } else if (status === "completed" || status === "error") {
            pendingQuestion.delete(sessionID);
            cancelReinforce(sessionID);
            if (lastQuestion.get(qid) !== "done") {
              lastQuestion.set(qid, "done");
              log(`question.replied sid=${sessionID} status=${status}`);
              forward("question.replied", { sessionID, part: { id: qid, type: "tool", tool: QUESTION_TOOL, state: { status } } });
            }
          }
        }
        return;
      }

      // While a question/permission is pending, ignore busy so it can't
      // overwrite blocked.
      if (type === "session.status") {
        const st = props.status?.type;
        if (st === "idle") {
          pendingQuestion.delete(sessionID);
          pendingPermission.delete(sessionID);
          cancelReinforce(sessionID);
        } else if (st === "busy" && (pendingQuestion.has(sessionID) || pendingPermission.has(sessionID))) {
          return;
        }
      }

      // session.updated fires often; only forward when title/directory changes.
      if (type === "session.updated") {
        const titleChanged = title && lastTitle.get(sessionID) !== title;
        const dirChanged = dir && lastDir.get(sessionID) !== dir;
        if (!titleChanged && !dirChanged) return;
      }
      if (title) lastTitle.set(sessionID, title);
      if (dir) lastDir.set(sessionID, dir);
      log(`${type} sid=${sessionID} title=${JSON.stringify(title ?? null)} dir=${JSON.stringify(dir ?? null)} status=${JSON.stringify(pick(props, "status"))}`);
      forward(type, { ...props, sessionID, session_name: title, session_dir: dir });
    },
  };
};
